### ISSUE TITLE
Rename to `not-hg`

### ISSUE THREAD

**Issue by ajoslin** [chrisinajar/not-mercury#2]
Easier to type, and `hg == mercury`

**Comment by chrisinajar** [comment]
I'm 50/50 on this, `hg` is my least favorite part of mercury because `hg` is already a [git alternative](https://www.mercurial-scm.org/)

but the bytes...

**Comment by ajoslin** [comment]
If you want to be crazy, https://www.npmjs.com/package/vapps for `virtual apps`?

**Comment by chrisinajar** [comment]
https://www.npmjs.com/package/nhg not `not-hg`, without appearing to be associated with mercurial at all.

**Comment by ajoslin** [comment]
:+1:

**Comment by chrisinajar** [comment]
Done and published, thanks for the great idea!
https://www.npmjs.com/package/nhg
